source "https://rubygems.org"

gem "rails", '~> 3.2.17'

gem 'bootstrap-sass', '~> 2.3.1.0'
gem "coffee-rails", "~> 3.2.1"
gem 'compass-rails'
gem 'jquery-rails', '~> 1.0.19'
gem "sass-rails", "~> 3.2.5"
gem "uglifier", ">= 1.0.3"
